// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function CheckAdmin() {
  return window['go']['main']['App']['CheckAdmin']();
}

export function CheckIP() {
  return window['go']['main']['App']['CheckIP']();
}

export function Connect(arg1) {
  return window['go']['main']['App']['Connect'](arg1);
}

export function Disconnect() {
  return window['go']['main']['App']['Disconnect']();
}

export function GetStats() {
  return window['go']['main']['App']['GetStats']();
}

export function LoadConfig() {
  return window['go']['main']['App']['LoadConfig']();
}

export function RelaunchAsAdmin() {
  return window['go']['main']['App']['RelaunchAsAdmin']();
}

export function SaveConfig(arg1) {
  return window['go']['main']['App']['SaveConfig'](arg1);
}
