// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {main} from '../models';

export function CheckAdmin():Promise<boolean>;

export function CheckIP():Promise<void>;

export function Connect(arg1:main.AppConfig):Promise<void>;

export function Disconnect():Promise<void>;

export function GetStats():Promise<main.GUIStats>;

export function LoadConfig():Promise<main.AppConfig>;

export function RelaunchAsAdmin():Promise<void>;

export function SaveConfig(arg1:main.AppConfig):Promise<void>;
